{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "fed634bf",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[3, 1, 6, 8, 6, 5, 9, 6, 1, 1, 6, 6, 6, 1, 1, 11, 6, 8, 5, 1, 1, 5, 6, 6, 12, 6, 15, 1, 8, 1, 8, 1, 6, 2, 8, 6, 6, 6, 6, 6, 6, 19, 6, 6, 6, 6, 20, 1, 19, 6, 6, 1, 6, 6, 15, 8, 6, 6, 6, 19, 6, 15, 2, 6, 1, 1, 11, 19, 23, 24, 2, 11, 7, 1, 7, 7, 6, 1, 18, 1, 6, 6, 6, 6, 6, 1, 19, 6, 1, 24, 6, 19, 7, 1, 11, 11, 1, 6, 13, 13, 6, 7, 13, 1, 6, 1, 9, 7, 6, 19, 15, 19, 1, 6, 19, 24, 6, 6, 29, 6, 6, 6, 1, 19, 1, 7, 7, 7, 6, 6, 6, 6, 6, 6, 6, 1, 1, 6, 6, 30, 6]\n",
      "[[0. 0. 0. ... 0. 0. 0.]\n",
      " [0. 1. 0. ... 0. 0. 0.]\n",
      " [0. 0. 0. ... 0. 0. 0.]\n",
      " ...\n",
      " [0. 0. 0. ... 0. 0. 0.]\n",
      " [0. 0. 0. ... 0. 0. 1.]\n",
      " [0. 0. 0. ... 0. 0. 0.]]\n",
      "(141, 31) (141, 32)\n",
      "Epoch 1/10\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "in user code:\n\n    File \"C:\\Users\\msok0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\engine\\training.py\", line 1160, in train_function  *\n        return step_function(self, iterator)\n    File \"C:\\Users\\msok0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\engine\\training.py\", line 1146, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\msok0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\engine\\training.py\", line 1135, in run_step  **\n        outputs = model.train_step(data)\n    File \"C:\\Users\\msok0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\engine\\training.py\", line 994, in train_step\n        loss = self.compute_loss(x, y, y_pred, sample_weight)\n    File \"C:\\Users\\msok0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\engine\\training.py\", line 1052, in compute_loss\n        return self.compiled_loss(\n    File \"C:\\Users\\msok0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\engine\\compile_utils.py\", line 265, in __call__\n        loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"C:\\Users\\msok0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\losses.py\", line 152, in __call__\n        losses = call_fn(y_true, y_pred)\n    File \"C:\\Users\\msok0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\losses.py\", line 272, in call  **\n        return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"C:\\Users\\msok0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\losses.py\", line 1486, in mean_squared_error\n        return backend.mean(tf.math.squared_difference(y_pred, y_true), axis=-1)\n\n    ValueError: Dimensions must be equal, but are 8 and 32 for '{{node mean_squared_error/SquaredDifference}} = SquaredDifference[T=DT_FLOAT](sequential_8/dense_26/Relu, IteratorGetNext:1)' with input shapes: [?,8], [?,32].\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Input \u001b[1;32mIn [11]\u001b[0m, in \u001b[0;36m<cell line: 90>\u001b[1;34m()\u001b[0m\n\u001b[0;32m     87\u001b[0m model\u001b[38;5;241m.\u001b[39mcompile(optimizer\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mrmsprop\u001b[39m\u001b[38;5;124m'\u001b[39m, loss\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mmse\u001b[39m\u001b[38;5;124m'\u001b[39m, metrics\u001b[38;5;241m=\u001b[39m[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124maccuracy\u001b[39m\u001b[38;5;124m'\u001b[39m])\n\u001b[0;32m     88\u001b[0m \u001b[38;5;66;03m# model.fit(np.array(x), np.array(y))\u001b[39;00m\n\u001b[1;32m---> 90\u001b[0m \u001b[43mmodel\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\u001b[43mx_encode\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43my_encode\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mbatch_size\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m14\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mepochs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m10\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[0;32m     91\u001b[0m \u001b[38;5;66;03m# model.fit(x, y, batch_size=14, epochs=10)\u001b[39;00m\n\u001b[0;32m     92\u001b[0m \u001b[38;5;66;03m# model.fit(x_temp, y_temp)\u001b[39;00m\n\u001b[0;32m     93\u001b[0m \u001b[38;5;66;03m# model.fit(x_temp, y_temp)\u001b[39;00m\n\u001b[0;32m     94\u001b[0m \u001b[38;5;66;03m# model.fit(x_temp, y_temp)\u001b[39;00m\n\u001b[0;32m     97\u001b[0m test_scores \u001b[38;5;241m=\u001b[39m model\u001b[38;5;241m.\u001b[39mevaluate(x_temp, y_temp)\n",
      "File \u001b[1;32m~\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\utils\\traceback_utils.py:70\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     67\u001b[0m     filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[0;32m     68\u001b[0m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[0;32m     69\u001b[0m     \u001b[38;5;66;03m# `tf.debugging.disable_traceback_filtering()`\u001b[39;00m\n\u001b[1;32m---> 70\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28mNone\u001b[39m\n\u001b[0;32m     71\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[0;32m     72\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[1;32m~\\AppData\\Local\\Temp\\__autograph_generated_filek1vla3rk.py:15\u001b[0m, in \u001b[0;36mouter_factory.<locals>.inner_factory.<locals>.tf__train_function\u001b[1;34m(iterator)\u001b[0m\n\u001b[0;32m     13\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m     14\u001b[0m     do_return \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mTrue\u001b[39;00m\n\u001b[1;32m---> 15\u001b[0m     retval_ \u001b[38;5;241m=\u001b[39m ag__\u001b[38;5;241m.\u001b[39mconverted_call(ag__\u001b[38;5;241m.\u001b[39mld(step_function), (ag__\u001b[38;5;241m.\u001b[39mld(\u001b[38;5;28mself\u001b[39m), ag__\u001b[38;5;241m.\u001b[39mld(iterator)), \u001b[38;5;28;01mNone\u001b[39;00m, fscope)\n\u001b[0;32m     16\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m:\n\u001b[0;32m     17\u001b[0m     do_return \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mFalse\u001b[39;00m\n",
      "\u001b[1;31mValueError\u001b[0m: in user code:\n\n    File \"C:\\Users\\msok0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\engine\\training.py\", line 1160, in train_function  *\n        return step_function(self, iterator)\n    File \"C:\\Users\\msok0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\engine\\training.py\", line 1146, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"C:\\Users\\msok0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\engine\\training.py\", line 1135, in run_step  **\n        outputs = model.train_step(data)\n    File \"C:\\Users\\msok0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\engine\\training.py\", line 994, in train_step\n        loss = self.compute_loss(x, y, y_pred, sample_weight)\n    File \"C:\\Users\\msok0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\engine\\training.py\", line 1052, in compute_loss\n        return self.compiled_loss(\n    File \"C:\\Users\\msok0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\engine\\compile_utils.py\", line 265, in __call__\n        loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"C:\\Users\\msok0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\losses.py\", line 152, in __call__\n        losses = call_fn(y_true, y_pred)\n    File \"C:\\Users\\msok0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\losses.py\", line 272, in call  **\n        return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"C:\\Users\\msok0\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\keras\\losses.py\", line 1486, in mean_squared_error\n        return backend.mean(tf.math.squared_difference(y_pred, y_true), axis=-1)\n\n    ValueError: Dimensions must be equal, but are 8 and 32 for '{{node mean_squared_error/SquaredDifference}} = SquaredDifference[T=DT_FLOAT](sequential_8/dense_26/Relu, IteratorGetNext:1)' with input shapes: [?,8], [?,32].\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import tensorflow as tf\n",
    "from tensorflow import keras\n",
    "from sklearn.preprocessing import LabelEncoder \n",
    "from keras.utils import to_categorical\n",
    "\n",
    "\n",
    "from keras.models import Sequential\n",
    "from keras.layers import *\n",
    "\n",
    "from setup import main\n",
    "\n",
    "data = main()\n",
    "\n",
    "# x = data.drop([\"IDE Interactions\", \"Timestamp Start\", \"Timestamp End\", \"Time Elapsed\", \"Time Between Last DA\", \"Speaker\"], axis = 1)\n",
    "# x = data[['Speaker','IDE State','Dialogue State','Intent', 'Delivery','Action','Tone']]\n",
    "# x = data[['Combined', 'Intent']]\n",
    "x = data['Dialogue State']\n",
    "# y = x[x['Speaker'] == 'P2']\n",
    "# x = x[x['Speaker'] == 'P1']\n",
    "# x.astype({'Combined' : 'category', 'Intent': 'category'}).dtypes\n",
    "\n",
    "total_states = []\n",
    "for i in range(1, 48):\n",
    "    total_states.append(\"S\" + str(i))\n",
    "\n",
    "# print(total_states)\n",
    "mapping = {}\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "y = x.loc[(x.index % 2 == 1)]\n",
    "x = x.loc[(x.index % 2 == 0)]\n",
    "\n",
    "for i in range(1,48):\n",
    "    mapping[total_states[i-1]] = i\n",
    "x = np.array(x)\n",
    "y = np.array(y)\n",
    "x = x[1:]\n",
    "y = y[1:]\n",
    "x = [mapping[i] for i in x]\n",
    "y = [mapping[i] for i in y]\n",
    "\n",
    "x_encode = to_categorical(x)\n",
    "y_encode = to_categorical(y)\n",
    "print(x)\n",
    "print(x_encode)\n",
    "\n",
    "\n",
    "print(x_encode.shape, y_encode.shape)\n",
    "\n",
    "# panda_x = pd.get_dummies(x)\n",
    "# panda_y = pd.get_dummies(y)\n",
    "\n",
    "\n",
    "# # x = x.iloc[1:]\n",
    "# # y = y.iloc[1:]\n",
    "# lb = LabelEncoder()\n",
    "# x_temp = lb.fit_transform(x)\n",
    "# y_temp = lb.fit_transform(y)\n",
    "\n",
    "# y = lb.fit_transform(y)\n",
    "# print(y.dtypes)\n",
    "# input_shape = (,2)\n",
    "model = Sequential(\n",
    "    [\n",
    "        # keras.layers.CategoryEncoding(num_tokens=2, output_)\n",
    "        keras.layers.Input(shape=(31,), name='input_1'),\n",
    "        keras.layers.Dense(16, activation=\"relu\"),\n",
    "        keras.layers.Dense(32, activation=\"relu\"),\n",
    "        keras.layers.Dense(8, activation=\"relu\"),\n",
    "        # keras.layers.Dense(25, activation=\"relu\"),\n",
    "        # keras.layers.Dense(10, activation=\"relu\"),\n",
    "    ]\n",
    "    )\n",
    "# model.add(Dense(142, activation='relu'))\n",
    "\n",
    "\n",
    "# layer = tf.keras.layers.CategoryEncoding(\n",
    "#     num_tokens=None, output_mode=\"one_hot\"\n",
    "# )\n",
    "\n",
    "# layerd\n",
    "# model.add(Activation('sigmoid'))\n",
    "model.compile(optimizer='rmsprop', loss='mse', metrics=['accuracy'])\n",
    "# model.fit(np.array(x), np.array(y))\n",
    "\n",
    "model.fit(x_encode, y_encode, batch_size=14, epochs=10)\n",
    "# model.fit(x, y, batch_size=14, epochs=10)\n",
    "# model.fit(x_temp, y_temp)\n",
    "# model.fit(x_temp, y_temp)\n",
    "# model.fit(x_temp, y_temp)\n",
    "\n",
    "\n",
    "test_scores = model.evaluate(x_temp, y_temp)\n",
    "print(\"Test loss:\", type(test_scores))\n",
    "print(\"Test accuracy:\", test_scores)\n",
    "# test_scores = model.evaluate(x, y, verbose=2)\n",
    "# print(test_scores)\n",
    "# def getStates():\n",
    "#     state = data['Combined'].where(data[\"Speaker\" == \"P1\"]).tolist()\n",
    "#     actions = data['Combined'].where(data[\"Speaker\" == \"P2\"]).tolist()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e736f822",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bff5c2d0",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "949ce401",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
